name: Build

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      # JDKのセットアップ
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # コンパイル
      - name: Run Compile
        run: ./gradlew assembleDebug

  lint:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 静的解析
      - name: Run Inspection
        run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Test
      - name: Run Test
        run: ./gradlew --stacktrace testDebugUnitTest
